'use strict';

const demoSubmissions = [
  {
    id: 'demo-001',
    createdAt: '2026-05-13T09:14:00.000Z',
    status: 'neu',
    photographerEmail: 'hallo@sandravogt.de',
    photographerName: 'Sandra Vogt Fotografie',
    wedding: {
      date: '2026-09-05',
      dateUnclear: false,
      ceremonyTime: '14:00',
      duration: 'Ganztag ~10h+',
    },
    location: {
      state: 'Bayern',
      city: 'München',
      types: ['Kirche', 'Hotel'],
      multipleLocations: 'Ja',
      address: 'St. Michael Kirche, Neuhauser Str. 6, 80333 München\nHotel Vier Jahreszeiten, Maximilianstr. 17, 80539 München',
    },
    wishes: {
      guestCount: '100–150',
      style: ['Romantisch & inszeniert', 'Klassisch & elegant'],
      videographer: 'Noch unklar',
      secondPhotographer: 'Ja',
    },
    budget: {
      range: '2.500–4.000 €',
      notes: 'Besonders wichtig sind uns die emotionalen Momente beim Einzug – am liebsten in natürlichem Licht. Ein Sonnenuntergangs-Shooting wäre ein Traum!',
    },
    contact: {
      partner1: 'Sophie',
      partner2: 'Jonas',
      email: 'sophie.jonas@gmail.com',
      phone: '+49 176 1234 5678',
      howFound: 'Instagram',
    },
  },
  {
    id: 'demo-002',
    createdAt: '2026-05-11T14:37:00.000Z',
    status: 'in_bearbeitung',
    photographerEmail: 'hallo@sandravogt.de',
    photographerName: 'Sandra Vogt Fotografie',
    wedding: {
      date: null,
      dateUnclear: true,
      ceremonyTime: 'noch unklar',
      duration: 'Trauung + Feier ~6h',
    },
    location: {
      state: 'Nordrhein-Westfalen',
      city: 'Köln',
      types: ['Freie Trauung', 'Schloss/Villa'],
      multipleLocations: 'Noch unklar',
    },
    wishes: {
      guestCount: '50–100',
      style: ['Reportage/Natürlich', 'Modern & Editorial'],
      videographer: 'Nur Foto',
      secondPhotographer: 'Noch unklar',
    },
    budget: {
      range: '1.500–2.500 €',
      notes: '',
    },
    contact: {
      partner1: 'Lena',
      partner2: 'Sarah',
      email: 'lena.sarah@web.de',
      phone: '',
      howFound: 'Google',
    },
  },
  {
    id: 'demo-003',
    createdAt: '2026-05-09T08:05:00.000Z',
    status: 'angebot_gesendet',
    photographerEmail: 'hallo@sandravogt.de',
    photographerName: 'Sandra Vogt Fotografie',
    wedding: {
      date: '2026-11-14',
      dateUnclear: false,
      ceremonyTime: '11:00',
      duration: 'Trauung + Feier ~6h',
    },
    location: {
      state: 'Hamburg',
      city: 'Hamburg',
      types: ['Standesamt', 'Outdoor'],
      multipleLocations: 'Ja',
      address: 'Standesamt Hamburg-Mitte, Caffamacherreihe 1–3, 20355 Hamburg\nPlanten un Blomen, Am Park 1, 20350 Hamburg',
    },
    wishes: {
      guestCount: 'unter 20',
      style: ['Modern & Editorial'],
      videographer: 'Ja, zusätzlich zum Foto',
      secondPhotographer: 'Nein',
    },
    budget: {
      range: 'über 4.000 €',
      notes: 'Wir möchten etwas sehr Außergewöhnliches – gerne auch ungewöhnliche Locations in der Stadt.',
    },
    contact: {
      partner1: 'Mia',
      partner2: 'Tobias',
      email: 'mia.tobias@icloud.com',
      phone: '+49 151 9876 5432',
      howFound: 'Empfehlung',
    },
  },
  {
    id: 'demo-004',
    createdAt: '2026-05-07T17:22:00.000Z',
    status: 'in_bearbeitung',
    photographerEmail: 'hallo@sandravogt.de',
    photographerName: 'Sandra Vogt Fotografie',
    wedding: {
      date: '2026-08-22',
      dateUnclear: false,
      ceremonyTime: '13:00',
      duration: 'Ganztag ~10h+',
    },
    location: {
      state: 'Baden-Württemberg',
      city: 'Stuttgart',
      types: ['Schloss/Villa', 'Hotel'],
      multipleLocations: 'Ja',
    },
    wishes: {
      guestCount: 'über 150',
      style: ['Klassisch & elegant', 'Romantisch & inszeniert'],
      videographer: 'Ja, zusätzlich zum Foto',
      secondPhotographer: 'Ja',
    },
    budget: {
      range: 'Möchte ich nicht angeben',
      notes: '',
    },
    contact: {
      partner1: 'Fatima',
      partner2: 'Jan',
      email: 'fatima.jan@outlook.com',
      phone: '+49 160 5555 4444',
      howFound: 'Hochzeitsportal',
    },
  },
  {
    id: 'demo-005',
    createdAt: '2026-05-05T11:03:00.000Z',
    status: 'neu',
    photographerEmail: 'hallo@sandravogt.de',
    photographerName: 'Sandra Vogt Fotografie',
    wedding: {
      date: '2027-05-01',
      dateUnclear: false,
      ceremonyTime: '15:00',
      duration: 'Nur Trauung ~2-3h',
    },
    location: {
      state: 'Berlin',
      city: 'Berlin',
      types: ['Standesamt'],
      multipleLocations: 'Nein',
    },
    wishes: {
      guestCount: '20–50',
      style: ['Reportage/Natürlich'],
      videographer: 'Nur Foto',
      secondPhotographer: 'Nein',
    },
    budget: {
      range: 'unter 1.500 €',
      notes: '',
    },
    contact: {
      partner1: 'Tom',
      partner2: 'Lukas',
      email: 'tom.lukas@gmx.de',
      phone: '+49 179 2233 4455',
      howFound: 'Instagram',
    },
  },
  {
    id: 'demo-006',
    createdAt: '2026-04-28T16:45:00.000Z',
    status: 'angebot_gesendet',
    photographerEmail: 'hallo@sandravogt.de',
    photographerName: 'Sandra Vogt Fotografie',
    wedding: {
      date: '2026-07-11',
      dateUnclear: false,
      ceremonyTime: '12:00',
      duration: 'Ganztag ~10h+',
    },
    location: {
      state: 'Hessen',
      city: 'Frankfurt am Main',
      types: ['Kirche', 'Schloss/Villa'],
      multipleLocations: 'Ja',
      address: 'Schloss Johannisberg, Johannisberg 1, 65366 Geisenheim',
    },
    wishes: {
      guestCount: '100–150',
      style: ['Klassisch & elegant'],
      videographer: 'Ja, zusätzlich zum Foto',
      secondPhotographer: 'Ja',
    },
    budget: {
      range: '2.500–4.000 €',
      notes: 'Wir heiraten auf Schloss Johannisberg – die Kulisse ist atemberaubend, das soll sich im Stil widerspiegeln.',
    },
    contact: {
      partner1: 'Laura',
      partner2: 'David',
      email: 'laura.david@gmail.com',
      phone: '+49 170 8877 6655',
      howFound: 'Empfehlung',
    },
  },
  {
    id: 'demo-007',
    createdAt: '2026-04-22T10:18:00.000Z',
    status: 'angebot_gesendet',
    photographerEmail: 'hallo@sandravogt.de',
    photographerName: 'Sandra Vogt Fotografie',
    wedding: {
      date: '2026-06-20',
      dateUnclear: false,
      ceremonyTime: '14:30',
      duration: 'Trauung + Feier ~6h',
    },
    location: {
      state: 'Sachsen',
      city: 'Dresden',
      types: ['Freie Trauung', 'Outdoor'],
      multipleLocations: 'Nein',
    },
    wishes: {
      guestCount: '50–100',
      style: ['Romantisch & inszeniert', 'Reportage/Natürlich'],
      videographer: 'Noch unklar',
      secondPhotographer: 'Nein',
    },
    budget: {
      range: '1.500–2.500 €',
      notes: '',
    },
    contact: {
      partner1: 'Julia',
      partner2: 'Ben',
      email: 'julia.ben@web.de',
      phone: '+49 152 3344 5566',
      howFound: 'Pinterest',
    },
  },
  {
    id: 'demo-008',
    createdAt: '2026-04-15T09:52:00.000Z',
    status: 'in_bearbeitung',
    photographerEmail: 'hallo@sandravogt.de',
    photographerName: 'Sandra Vogt Fotografie',
    wedding: {
      date: null,
      dateUnclear: true,
      ceremonyTime: 'noch unklar',
      duration: 'Ganztag ~10h+',
    },
    location: {
      state: 'Bayern',
      city: 'Garmisch-Partenkirchen',
      types: ['Kirche', 'Outdoor'],
      multipleLocations: 'Ja',
    },
    wishes: {
      guestCount: '50–100',
      style: ['Romantisch & inszeniert'],
      videographer: 'Nur Foto',
      secondPhotographer: 'Ja',
    },
    budget: {
      range: 'über 4.000 €',
      notes: 'Bergpanorama ist uns sehr wichtig. Wir stellen uns ein After-Wedding-Shooting auf der Alm vor.',
    },
    contact: {
      partner1: 'Katharina',
      partner2: 'Michael',
      email: 'kathi.michi@icloud.com',
      phone: '+49 162 9988 7766',
      howFound: 'Instagram',
    },
  },
  {
    id: 'demo-009',
    createdAt: '2026-04-08T13:30:00.000Z',
    status: 'angebot_gesendet',
    photographerEmail: 'hallo@sandravogt.de',
    photographerName: 'Sandra Vogt Fotografie',
    wedding: {
      date: '2026-10-03',
      dateUnclear: false,
      ceremonyTime: '16:00',
      duration: 'Trauung + Feier ~6h',
    },
    location: {
      state: 'Rheinland-Pfalz',
      city: 'Koblenz',
      types: ['Freie Trauung', 'Hotel'],
      multipleLocations: 'Nein',
    },
    wishes: {
      guestCount: '20–50',
      style: ['Modern & Editorial'],
      videographer: 'Nur Foto',
      secondPhotographer: 'Nein',
    },
    budget: {
      range: '1.500–2.500 €',
      notes: '',
    },
    contact: {
      partner1: 'Sarah',
      partner2: 'Niko',
      email: 'sarah.niko@gmail.com',
      phone: '',
      howFound: 'Google',
    },
  },
  {
    id: 'demo-010',
    createdAt: '2026-03-29T08:11:00.000Z',
    status: 'angebot_gesendet',
    photographerEmail: 'hallo@sandravogt.de',
    photographerName: 'Sandra Vogt Fotografie',
    wedding: {
      date: '2026-05-30',
      dateUnclear: false,
      ceremonyTime: '11:00',
      duration: 'Ganztag ~10h+',
    },
    location: {
      state: 'Bayern',
      city: 'Regensburg',
      types: ['Standesamt', 'Schloss/Villa'],
      multipleLocations: 'Ja',
    },
    wishes: {
      guestCount: '100–150',
      style: ['Klassisch & elegant', 'Romantisch & inszeniert'],
      videographer: 'Ja, zusätzlich zum Foto',
      secondPhotographer: 'Ja',
    },
    budget: {
      range: 'über 4.000 €',
      notes: 'Wir legen sehr viel Wert auf Detailaufnahmen – Blumen, Ringe, Tischdekoration. Das soll unbedingt ausführlich dokumentiert werden.',
    },
    contact: {
      partner1: 'Emma',
      partner2: 'Alexander',
      email: 'emma.alex@outlook.de',
      phone: '+49 175 1122 3344',
      howFound: 'Hochzeitsportal',
    },
  },
];

module.exports = demoSubmissions;
